name: Build & Deploy (Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyterlab nbconvert

      - name: Execute & export notebooks -> notebooks
        run: |
          mkdir -p notebooks
          python - <<'PY'
import pathlib, subprocess, sys
nb_list = [str(p) for p in pathlib.Path(".").rglob("*.ipynb") if ".ipynb_checkpoints" not in str(p)]
if not nb_list:
    print("No notebooks found", file=sys.stderr); sys.exit(0)
for nb in nb_list:
    print("Executing & exporting:", nb, flush=True)
    subprocess.run(["jupyter","nbconvert",nb,"--to","notebook","--execute","--inplace","--ExecutePreprocessor.timeout=1200"], check=True)
    subprocess.run(["jupyter","nbconvert",nb,"--to","html","--template","lab","--output-dir","notebooks"], check=True)
PY

      - name: Inject cache-busting SHAs into scenario pages
        run: |
          SHA_SHORT=$(echo "${GITHUB_SHA}" | cut -c1-8)
          for f in scenarios/*.html; do
            sed -i "s|notebooks/\([A-Za-z0-9_-]\+\)\.html|notebooks/\1.html?v=${SHA_SHORT}|g" "$f"
          done

      - name: Build _site (copy static + exported)
        run: |
          mkdir -p _site
          cp -r index.html assets plots scenarios _site/ || true
          cp -r notebooks _site/
          echo "Built files:"; find _site -type f | wc -l

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
